stages:
  - build
  - test
  - coverage
  - deploy

install-dependencies:
  stage: build
  tags:
    - back_demo
  script:
    - echo "Installing dependencies..."
    - pip install -r requirements.txt
    - echo "Dependencies installed."

unit-test-job:
  stage: test
  tags:
    - back_demo
  script:
    - echo "Running unit tests..."
    - python -m unittest discover
    - echo "Unit tests complete."

lint-test-job:
  stage: test
  tags:
    - back_demo
  script:
    - pip install pylint
    - find . -name "*.py" ! -path "./tests/*" -exec pylint {} \;

coverage-job:
  stage: coverage
  tags:
    - back_demo
  script:
    - pip install coverage
    - coverage run --source=. -m unittest discover
    - coverage report -m
    - coverage xml -o coverage.xml
  artifacts:
    paths:
      - coverage.xml

pre-deploy:
  stage: deploy
  tags:
    - back_demo
  script:
    - echo "Performing database migration..."
    - python db.py
    - echo "Database migration complete."
